"""Add foreign key between Animal and Event

Revision ID: cb052218d78a
Revises: 
Create Date: 2025-10-16 22:51:22.270888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = 'cb052218d78a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###